### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by florianbegusch** [zhanknight/SMMTZC---Simple-Menubar-Multi-Time-Zone-Clock#7]
Hi,

could you build a .dmg package to have your app as an install-able?

I would really appreciate it if you were to find the time. Obviously I understand if you do not

Cheers

**Comment by zhanknight** [comment]
Hey! 

I realize this is nearly two years late, but I picked this project back up, updated it, and shared a release in the repo. You can [get it here](https://github.com/zhanknight/SMMTZC---Simple-Menubar-Multi-Time-Zone-Clock/releases). I hope it's useful for you still!

**Comment by florianbegusch** [comment]
Appreciated!

Have a workaround with a xbar.app plugin for now.
But I might switch and I had a colleague ask for a recommendation & I did not like any of the other apps.

Installer works on my end. Thank you.
